In [1]:
#NumPy aka Numerical Python
pip install numpy

SyntaxError: invalid syntax (2831607023.py, line 2)

In [2]:
pip install numPy

^C
Note: you may need to restart the kernel to use updated packages.
Defaulting to user installation because normal site-packages is not writeable


In [1]:
pip install numpy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [3]:
#Creating numPy Array
import numpy as np

array = np.array([5, 10, 15, 20, 25])
print("Element in array:", array)


Element in array: [ 5 10 15 20 25]


In [4]:
#Array Operating: Let's find average of above array elements

average = np.mean(array)
print("average of above array is", average)

average of above array is 15.0


In [11]:
#Multi dimensional array

height_cm = np.array([[100, 110, 111], [110, 105, 125], [120, 125, 130]])
print("Height of 2022D First benchers:\n", height_cm)

Height of 2022D First benchers:
 [[100 110 111]
 [110 105 125]
 [120 125 130]]


In [12]:
#Array indexing and slicing

first_bench_student_height = height_cm[0]
print("First bench students heights:", first_bench_student_height)

bata_height = height_cm [1] [2]
print("Bata height is", bata_height)

last_bench_height = height_cm[:-1]
print("last bench students heights are", last_bench_height)

First bench students heights: [100 110 111]
Bata height is 125
last bench students heights are [[100 110 111]
 [110 105 125]]


In [16]:
#Converting the temperature from C to F and C to K

temperature = np.array([[20, 25, 29], [19, 23, 22], [18, 20, 37]])
f = (temperature * 9/5) + 32
print("Temperature in F is \n", f)

k = (temperature + 273.15)
print("\nTemperature in Kelvin is\n", k)

Temperature in F is 
 [[68.  77.  84.2]
 [66.2 73.4 71.6]
 [64.4 68.  98.6]]

Temperature in Kelvin is
 [[293.15 298.15 302.15]
 [292.15 296.15 295.15]
 [291.15 293.15 310.15]]


In [20]:
#Linear Algebra Operation 

sales = np.array([[500, 100, 200], [750, 1000, 1500]])
quantity = np.array([[10, 20, 30], [100, 200, 50]]) 

revenue = np.dot(sales, quantity.T)
print("total revenue:\n", revenue)

total revenue:
 [[ 13000  80000]
 [ 72500 350000]]


In [26]:
#zeros and ones (matrix)

print("zeros matrix 3*3 is:\n", np.zeros((3,3), dtype = int))
print("ones matrix 3*3 is:\n", np.ones((3,3), dtype = int))
print("\nEye matrix 5*5 is:\n", np.eye(5, dtype = int))

zeros matrix 3*3 is:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]
ones matrix 3*3 is:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

Eye matrix 5*5 is:
 [[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [28]:
#create a 1D NumPy array values ranging from 0 to 9

array_1D = np.arange(10)
print("\n1D Array_1D", array_1D)

#create a 2D NumPY array with the shape (3,3) containing the above value 1 to 10
array_2D = np.arange(1,10).reshape(3,3)
print("\n 2D Array:\n", array_2D)


1D Array_1D [0 1 2 3 4 5 6 7 8 9]

 2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [29]:
#perform element-wise addition, subtraction, multiplication, and division on 1D Array [1, 2, 3] and [4, 5, 6]

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

addition = array1 + array2
subtraction = array2 - array1
multiplication = array1 * array2
division = array2 / array1

print(addition, subtraction, multiplication, division)   

[5 7 9] [3 3 3] [ 4 10 18] [4.  2.5 2. ]


In [1]:
#May-10-Monday
#Calculate the mean, median, standard deviation, and variance of 1D array

import numpy as np

array = np.array([10, 20, 30, 40, 50, 100])
mean = np.mean(array)
median = np.median(array)
std_dev = np.std(array)
variance = np.var(array)#
print("\nMean:", mean)
print("\nMedian:", median)
print("\nStd_Deviation:", std_dev)
print("\nVariance:", variance)


Mean: 41.666666666666664

Median: 35.0

Std_Deviation: 29.1070819942883

Variance: 847.2222222222222


In [4]:
#logical Operation (and, or, etc.)
#Given array [20, 50, 70, 90, 150, 200]
#Return an array with elements that are greater than 70

array = np.array([20, 50, 70, 90, 150, 200])
result = array[array > 70]
print("An array with elements that are greater than 70 is:\n", result)


An array with elements that are greater than 70 is:
 [ 90 150 200]


In [5]:
#Create 3x3 matrix with random values between 0 and 1

random_matrix = np.random.random((3,3))
print("3x3 matrix is:\n", random_matrix)

3x3 matrix is:
 [[0.79028416 0.68537638 0.8554098 ]
 [0.80594005 0.58505483 0.89892371]
 [0.18527486 0.91930622 0.61465187]]


In [13]:
#Create an array of 10 random integers between 50 and 100

random_int_matrix = np.random.randint(50, 100, 9).reshape(3,3)
print(random_int_matrix)


print("\nLet's multiply given matrix by sclar value of 10:\n") #multiplying the matrix by 10
result = random_int_matrix * 10
print(result)

[[65 62 55]
 [61 87 59]
 [77 57 99]]

Let's multiply given matrix by sclar value of 10:

[[650 620 550]
 [610 870 590]
 [770 570 990]]


In [16]:
#Create an array with some missing values (NaNs) and calculate the mean, ignoring NaNs

array_with_missing_values = np.array([10, 20, np.nan, 50, 70, np.nan])
print(array_with_missing_values)
mean = np.nanmean(array_with_missing_values)
print("Mean:", mean)

[10. 20. nan 50. 70. nan]
Mean: 37.5


In [17]:
#Apply the sine function to each element in the array
#[0, pi/2, pi, 3*pi/2, 2*pi]

sine_array = [0, np.pi/2, np.pi, 3*np.pi/2, 2*np.pi]
sine_values = np.sin(sine_array)
print(sine_values)

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00
 -2.4492936e-16]


In [18]:
#Find the unique elements in an array [1,1,10,3,3,5,5,6,6,88,9,19,34]

repeated_values = np.array([1,1,10,3,3,5,5,6,6,88,9,19,34])
unique_values  = np.unique(repeated_values)
print(unique_values)


[ 1  3  5  6  9 10 19 34 88]


In [19]:
#Sorting the array in ascending order

unsorted_array = np.array([100, 200, 150, 2, 40, 21, 32, 90, 1])
sorted_array = np.sort(unsorted_array)
print(sorted_array)

[  1   2  21  32  40  90 100 150 200]


In [25]:
#Find the shape, size, and the number of dimension in an array 

array_1d = np.array([1])
array_2d = np.random.random([2,3])
array_3d = np.random.random([4,9,7])

print(array_1d)
print(array_2d)
print(array_3d)

#shape
shape_1d = array_1d.shape
shape_2d = array_2d.shape
shape_3d = array_3d.shape

#size
size_1d = array_1d.size
size_2d = array_2d.size
size_3d = array_3d.size

#dimension
dimension_1d = array_1d.ndim
dimension_2d = array_2d.ndim
dimension_3d = array_3d.ndim


print("shape of 1D array:",shape_1d)
print("shape of 2D array:",shape_2d)
print("shape of 3D array:",shape_3d)

print("size of 1D array:",size_1d)
print("size of 2D array:",size_2d)
print("size of 3D array:",size_3d)

print(dimension_1d)
print(dimension_2d)
print(dimension_3d)


[1]
[[0.12984963 0.99755874 0.85733663]
 [0.33510191 0.65912826 0.99193013]]
[[[0.00678813 0.10919829 0.37127506 0.98223643 0.86041794 0.09977634
   0.12233432]
  [0.68575445 0.37460692 0.58864333 0.67518668 0.00401073 0.82475542
   0.40310869]
  [0.00171614 0.94790952 0.02755226 0.70594063 0.07411865 0.9422783
   0.64496161]
  [0.38106036 0.19375158 0.30293841 0.32408273 0.28352234 0.89013829
   0.99650047]
  [0.91499082 0.46629056 0.5861181  0.75115851 0.48704984 0.53777485
   0.1794656 ]
  [0.94413085 0.57409463 0.22506721 0.8813913  0.69393121 0.57878946
   0.88016214]
  [0.36103119 0.2212357  0.79331806 0.0451645  0.80391636 0.55445234
   0.14135316]
  [0.63944556 0.65262806 0.51497429 0.84088142 0.15993166 0.92327855
   0.43219772]
  [0.47923532 0.22864243 0.10071017 0.87648225 0.22440431 0.16087858
   0.13781444]]

 [[0.82257988 0.11224161 0.55625312 0.03520321 0.80925564 0.67143586
   0.31534379]
  [0.98384547 0.83509536 0.26500057 0.66728649 0.47137676 0.18246651
   0.18982063

In [ ]:
pip install

In [2]:
#Web Scraping 

import request
from bs4 import BeautifulSoup

def scrape_headings(url): 
    response = requests.get(url) #Send a GET request to the url
    soup = BeautifulSoup(response.content, "html.praser") #parse the HTML content using BeautifulSoup
    headings = soup.find_all(["h1", "h2", "h3", "h4", "h5"]) #find all the headings elements
   for heading in headings: #print the text of each headings
       print(heading.text.strip())

input_url = input("Enter the URL to scrape:")  #Prompt the user to enter the url
scrape_headings(input_url)  #Call the scrape_headings function with input url

IndentationError: unindent does not match any outer indentation level (<tokenize>, line 10)